### ISSUE TITLE
Migrating to v1.0.0...

### ISSUE THREAD

**Issue by james-pcdr** [python-can-define-radio/sdr-course#29]
EDIT: see later comment

**Comment by james-pcdr** [comment]
EDIT: see later comment

**Comment by james-pcdr** [comment]
EDIT: see later comment

**Comment by james-pcdr** [comment]
Phase 0: Convert `makeRealWave`, `makeComplexWave`, or any variations to simply `makeWave`. Also, ensure they are consistently using the old signature of `makeWave` (not the new `make_wave`). Finally, ensure `generate_ook_modulated_example_data` still works as described on any lessons.

...Wait for [Pcdr issue 29](https://github.com/python-can-define-radio/pcdr/issues/29)  

Phase 1: Change lessons to say "for version 1.x, use `v0_compat`". 

...Wait for when the key functions are moved from `pcdr.unstable` to `pcdr` (ETA: approx end of 2024)

Phase 2: change lessons to use those

**Comment by Elijah-cyber7** [comment]
This seems interesting, is there anything I can help with ?

**Comment by james-pcdr** [comment]
@Elijah-cyber7 Sure. I've moved the pcdr code to [its own repository](https://github.com/python-can-define-radio/pcdr). 

My overall approach to the pcdr project is different from a few months ago, so I'm no longer focusing on wrapping individual GNU Radio blocks (so, for example, I'm not going doing [this](https://github.com/python-can-define-radio/sdr-course/issues/13) any more). 

I'll get organized on Wed or Thur so I can start tagging you on more issues. I'll start by tagging you on [pcdr issue 36](https://github.com/python-can-define-radio/pcdr/issues/36).

**Comment by james-pcdr** [comment]
Going to postpone phase 2 indefinitely. Other phases are done.
